export type PaymentIconId =
  | "house"
  | "wallet"
  | "card"
  | "car"
  | "fuel"
  | "scooter"
  | "calendar"
  | "people"
  | "school"
  | "badge"
  | "sofa"
  | "envelope"
  | "gift"
  | "coffee"
  | "heart"
  // Identificadores históricos que siguen llegando desde Core/Home.
  | "stethoscope"
  | "paw-print"
  | "receipt"
  | "shopping-cart"
  | "shopping-bag"
  | "briefcase"
  | "shapes";
